export const levelOptions = [
  { label: "A1 (iniciante 1)", value: "a1" },
  { label: "A2 (iniciante 2)", value: "a2" },
  { label: "B1 (iniciante 1)", value: "b1" },
  { label: "B2 (iniciante 2)", value: "b2" },
  { label: "C1 (avançado 1)", value: "c1" },
  { label: "C2 (avançado 2)", value: "c2" },
];

export const accentOptions = {
  pt: [
    { label: "Americano", value: "american" },
    { label: "Britânico", value: "british" },
    { label: "Australiano", value: "australian" },
    { label: "Sul Africano", value: "south-african" },
    { label: "Outro", value: "other" },
  ],
  en: [
    { label: "American", value: "american" },
    { label: "British", value: "british" },
    { label: "Australian", value: "australian" },
    { label: "South African", value: "south-african" },
    { label: "Other", value: "other" },
  ],
  es: [
    { label: "Americano", value: "american" },
    { label: "Británico", value: "british" },
    { label: "Australiano", value: "australian" },
    { label: "Sudafricano", value: "south-african" },
    { label: "Otro", value: "other" },
  ],
};

export const genreOptions = {
  pt: [
    { label: "Ação", value: "action" },
    { label: "Comédia", value: "comedy" },
    { label: "Drama", value: "drama" },
    { label: "Ficção Científica", value: "science-fiction" },
    { label: "Romance", value: "romance" },
    { label: "Terror", value: "horror" },
    { label: "Aventura", value: "adventure" },
    { label: "Mistério", value: "mystery" },
    { label: "Documentário", value: "documentary" },
    { label: "Fantasia", value: "fantasy" },
    { label: "Animação", value: "animation" },
    { label: "Suspense", value: "thriller" },
    { label: "Musical", value: "musical" },
  ],
  en: [
    { label: "Action", value: "action" },
    { label: "Comedy", value: "comedy" },
    { label: "Drama", value: "drama" },
    { label: "Science Fiction", value: "science-fiction" },
    { label: "Romance", value: "romance" },
    { label: "Horror", value: "horror" },
    { label: "Adventure", value: "adventure" },
    { label: "Mystery", value: "mystery" },
    { label: "Documentary", value: "documentary" },
    { label: "Fantasy", value: "fantasy" },
    { label: "Animation", value: "animation" },
    { label: "Thriller", value: "thriller" },
    { label: "Musical", value: "musical" },
  ],
  es: [
    { label: "Acción", value: "action" },
    { label: "Comedia", value: "comedy" },
    { label: "Drama", value: "drama" },
    { label: "Ciencia Ficción", value: "science-fiction" },
    { label: "Romántico", value: "romance" },
    { label: "Terror", value: "horror" },
    { label: "Aventura", value: "adventure" },
    { label: "Misterio", value: "mystery" },
    { label: "Documental", value: "documentary" },
    { label: "Fantasía", value: "fantasy" },
    { label: "Animación", value: "animation" },
    { label: "Suspenso", value: "thriller" },
    { label: "Musical", value: "musical" },
  ],
};
